#ifndef _DEF_H_

#define _DEF_H_

#define SERCOM3_SPI_nCS					GPIO_PA18
#define SERCOM3_SPI_SCK					GPIO_PA17
#define SERCOM3_SPI_MOSI				GPIO_PA16
#define SERCOM3_SPI_MISO				GPIO_PA19

#define SERCOM4_SPI_nCS					GPIO_PB10
#define SERCOM4_SPI_SCK					GPIO_PB09
#define SERCOM4_SPI_MOSI				GPIO_PB08
#define SERCOM4_SPI_MISO				GPIO_PB11

#define SERCOM2_SPI_nCS					GPIO_PA14
#define SERCOM2_SPI_SCK					GPIO_PA13
#define SERCOM2_SPI_MOSI				GPIO_PA12
#define SERCOM2_SPI_MISO				GPIO_PA15

#define SERCOM_FT8XX SERCOM2
#define FT8XX_nCS SERCOM2_SPI_nCS

#define SERCOM_RTC SERCOM3
#define RTC_CS SERCOM3_SPI_nCS



#define MMC_ENABLE		GPIO_PA03
#define CARD_DETECT		GPIO_PA04
#define FT_nRESET		GPIO_PA05
#define VIDEO_nINT		GPIO_PA06



#endif



