#ifndef _USER_GPIO_H_

#define _USER_GPIO_H_



//#define	PIN_FUNCTION_A	0
//#define	PIN_FUNCTION_B	1
//#define	PIN_FUNCTION_C	2
//#define	PIN_FUNCTION_D	3
//#define	PIN_FUNCTION_E	4
//#define	PIN_FUNCTION_F	5
//#define	PIN_FUNCTION_G	6
//#define	PIN_FUNCTION_H	7
typedef enum
{
	PIN_FUNCTION_A=0,
	PIN_FUNCTION_B,
	PIN_FUNCTION_C,
	PIN_FUNCTION_D,
	PIN_FUNCTION_E,
	PIN_FUNCTION_F,
	PIN_FUNCTION_G,
	PIN_FUNCTION_H,
	PIN_FUNCTION_NOUSE=0xFF,
}GPIO_FUNCTION;

typedef enum 		
{		
	GPIO_00	=0,
	GPIO_01	,
	GPIO_02	,
	GPIO_03	,
	GPIO_04	,
	GPIO_05	,
	GPIO_06	,
	GPIO_07	,
	GPIO_08	,
	GPIO_09	,
	GPIO_10	,
	GPIO_11	,
	GPIO_12	,
	GPIO_13	,
	GPIO_14	,
	GPIO_15	,
	GPIO_16	,
	GPIO_17	,
	GPIO_18	,
	GPIO_19	,
	GPIO_20	,
	GPIO_21	,
	GPIO_22	,
	GPIO_23	,
	GPIO_24	,
	GPIO_25	,
	GPIO_26	,
	GPIO_27	,
	GPIO_28	,
	GPIO_29	,
	GPIO_30	,
	GPIO_31	,

	GPIO_END=0xFF,
}GPIO;



//#define	USE_GPIO_PORT		0x00
//#define	USE_GPIO_FUNC		0x01
typedef enum
{
	USE_GPIO_PORT=0,
	USE_GPIO_FUNC,
}GPIO_MODE;

/*
bit7:DIR
bit6:INEN
bit5:PULLEN
bit4:DRIVE
bit0:outport
*/
#define USE_GPIO_DISCONNECT			0x00
#define USE_GPIO_OUTPUT				0x80
#define USE_GPIO_INPUT				0x40
#define USE_GPIO_BIDIRECTION		(USE_GPIO_OUTPUT|USE_GPIO_INPUT)
#define USE_GPIO_FORCE_PULL			0x20
#define USE_GPIO_DRIVE_STRONG		0x10
#define USE_GPIO_FORCE_PULLUP		(USE_GPIO_FORCE_PULL|0x01)
#define USE_GPIO_FORCE_PULLDOWN		(USE_GPIO_FORCE_PULL|0x00)



#define WRCONFIG_HWSEL		0x80000000
#define WRCONFIG_WRPMUX		0x10000000
#define WRCONFIG_PMUXEN		0x00010000
#define WRCONFIG_WRPINCFG	0x40000000
#define WRCONFIG_INEN		0x00020000
#define WRCONFIG_PULLEN		0x00040000
#define WRCONFIG_DRVSTR		0x00400000



typedef struct GPIO_SETTING_TBL
{
	GPIO port;
	GPIO_MODE mode;
	unsigned char config;
	unsigned char func;
}GPIO_INIT_TABLE;




int GpioPortInit( GPIO_INIT_TABLE *tbl );
int GpioBitOut( GPIO port,unsigned char bit );
int GpioBitIn( GPIO port );




#define	GPIO_BITMASK	0x1F
#define	GPIO_BITIGNORE	0x20
#define	GPIO_PORTMASK	0xC0

#define	PORTA_GROUP		0x00
#define	PORTB_GROUP		0x40
#define	PORTC_GROUP		0x60
#define	PORTD_GROUP		0x80
#define	PORTA_IGNORE	0x20






#define	PA00_USE_EXTINT_0	PIN_FUNCTION_A
#define	PA01_USE_EXTINT_1	PIN_FUNCTION_A
#define	PA02_USE_EXTINT_2	PIN_FUNCTION_A
#define	PA03_USE_EXTINT_3	PIN_FUNCTION_A
#define	PB08_USE_EXTINT_8	PIN_FUNCTION_A
#define	PB09_USE_EXTINT_9	PIN_FUNCTION_A
#define	PA04_USE_EXTINT_4	PIN_FUNCTION_A
#define	PA05_USE_EXTINT_5	PIN_FUNCTION_A
#define	PA06_USE_EXTINT_6	PIN_FUNCTION_A
#define	PA07_USE_EXTINT_7	PIN_FUNCTION_A
#define	PA08_USE_NMI		PIN_FUNCTION_A
#define	PA09_USE_EXTINT_9	PIN_FUNCTION_A
#define	PA10_USE_EXTINT_10	PIN_FUNCTION_A
#define	PA11_USE_EXTINT_11	PIN_FUNCTION_A
#define	PB10_USE_EXTINT_10	PIN_FUNCTION_A
#define	PB11_USE_EXTINT_11	PIN_FUNCTION_A
#define	PA12_USE_EXTINT_12	PIN_FUNCTION_A
#define	PA13_USE_EXTINT_13	PIN_FUNCTION_A
#define	PA14_USE_EXTINT_14	PIN_FUNCTION_A
#define	PA15_USE_EXTINT_15	PIN_FUNCTION_A
#define	PA16_USE_EXTINT_0	PIN_FUNCTION_A
#define	PA17_USE_EXTINT_1	PIN_FUNCTION_A
#define	PA18_USE_EXTINT_2	PIN_FUNCTION_A
#define	PA19_USE_EXTINT_3	PIN_FUNCTION_A
#define	PA20_USE_EXTINT_4	PIN_FUNCTION_A
#define	PA21_USE_EXTINT_5	PIN_FUNCTION_A
#define	PA22_USE_EXTINT_6	PIN_FUNCTION_A
#define	PA23_USE_EXTINT_7	PIN_FUNCTION_A
#define	PA24_USE_EXTINT_12	PIN_FUNCTION_A
#define	PA25_USE_EXTINT_13	PIN_FUNCTION_A
#define	PB22_USE_EXTINT_6	PIN_FUNCTION_A
#define	PB23_USE_EXTINT_7	PIN_FUNCTION_A
#define	PA27_USE_EXTINT_15	PIN_FUNCTION_A
#define	PA28_USE_EXTINT_8	PIN_FUNCTION_A
#define	PA30_USE_EXTINT_10	PIN_FUNCTION_A
#define	PA31_USE_EXTINT_11	PIN_FUNCTION_A
#define	PB02_USE_EXTINT_2	PIN_FUNCTION_A
#define	PB03_USE_EXTINT_3	PIN_FUNCTION_A
#define	PB04_USE_EXTINT_4	PIN_FUNCTION_A
#define	PB05_USE_EXTINT_5	PIN_FUNCTION_A
#define	PB06_USE_EXTINT_6	PIN_FUNCTION_A
#define	PB07_USE_EXTINT_7	PIN_FUNCTION_A
#define	PB12_USE_EXTINT_12	PIN_FUNCTION_A
#define	PB13_USE_EXTINT_13	PIN_FUNCTION_A
#define	PB14_USE_EXTINT_14	PIN_FUNCTION_A
#define	PB15_USE_EXTINT_15	PIN_FUNCTION_A
#define	PB16_USE_EXTINT_0	PIN_FUNCTION_A
#define	PB17_USE_EXTINT_1	PIN_FUNCTION_A
#define	PB30_USE_EXTINT_14	PIN_FUNCTION_A
#define	PB31_USE_EXTINT_15	PIN_FUNCTION_A
#define	PB00_USE_EXTINT_0	PIN_FUNCTION_A
#define	PB01_USE_EXTINT_1	PIN_FUNCTION_A


#define	PA00_USE_ANALOG	PIN_FUNCTION_B
#define	PA01_USE_ANALOG	PIN_FUNCTION_B
#define	PA02_USE_ANALOG	PIN_FUNCTION_B
#define	PA03_USE_ANALOG	PIN_FUNCTION_B
#define	PB08_USE_ANALOG	PIN_FUNCTION_B
#define	PB09_USE_ANALOG	PIN_FUNCTION_B
#define	PA04_USE_ANALOG	PIN_FUNCTION_B
#define	PA05_USE_ANALOG	PIN_FUNCTION_B
#define	PA06_USE_ANALOG	PIN_FUNCTION_B
#define	PA07_USE_ANALOG	PIN_FUNCTION_B
#define	PA08_USE_ANALOG	PIN_FUNCTION_B
#define	PA09_USE_ANALOG	PIN_FUNCTION_B
#define	PA10_USE_ANALOG	PIN_FUNCTION_B
#define	PA11_USE_ANALOG	PIN_FUNCTION_B
#define	PB10_USE_ANALOG	PIN_FUNCTION_B
#define	PB11_USE_ANALOG	PIN_FUNCTION_B
#define	PA12_USE_ANALOG	PIN_FUNCTION_B
#define	PA13_USE_ANALOG	PIN_FUNCTION_B
#define	PA14_USE_ANALOG	PIN_FUNCTION_B
#define	PA15_USE_ANALOG	PIN_FUNCTION_B
#define	PA16_USE_ANALOG	PIN_FUNCTION_B
#define	PA17_USE_ANALOG	PIN_FUNCTION_B
#define	PA18_USE_ANALOG	PIN_FUNCTION_B
#define	PA19_USE_ANALOG	PIN_FUNCTION_B
#define	PA20_USE_ANALOG	PIN_FUNCTION_B
#define	PA21_USE_ANALOG	PIN_FUNCTION_B
#define	PA22_USE_ANALOG	PIN_FUNCTION_B
#define	PA23_USE_ANALOG	PIN_FUNCTION_B
#define	PA24_USE_ANALOG	PIN_FUNCTION_B
#define	PA25_USE_ANALOG	PIN_FUNCTION_B
#define	PB22_USE_ANALOG	PIN_FUNCTION_B
#define	PB23_USE_ANALOG	PIN_FUNCTION_B
#define	PA27_USE_ANALOG	PIN_FUNCTION_B
#define	PA28_USE_ANALOG	PIN_FUNCTION_B
#define	PA30_USE_ANALOG	PIN_FUNCTION_B
#define	PA31_USE_ANALOG	PIN_FUNCTION_B
#define	PB02_USE_ANALOG	PIN_FUNCTION_B
#define	PB03_USE_ANALOG	PIN_FUNCTION_B
#define	PB04_USE_ANALOG	PIN_FUNCTION_B
#define	PB05_USE_ANALOG	PIN_FUNCTION_B
#define	PB06_USE_ANALOG	PIN_FUNCTION_B
#define	PB07_USE_ANALOG	PIN_FUNCTION_B
#define	PB12_USE_ANALOG	PIN_FUNCTION_B
#define	PB13_USE_ANALOG	PIN_FUNCTION_B
#define	PB14_USE_ANALOG	PIN_FUNCTION_B
#define	PB15_USE_ANALOG	PIN_FUNCTION_B
#define	PB16_USE_ANALOG	PIN_FUNCTION_B
#define	PB17_USE_ANALOG	PIN_FUNCTION_B
#define	PB30_USE_ANALOG	PIN_FUNCTION_B
#define	PB31_USE_ANALOG	PIN_FUNCTION_B
#define	PB00_USE_ANALOG	PIN_FUNCTION_B
#define	PB01_USE_ANALOG	PIN_FUNCTION_B


#define	PA00_USE_SERCOM1_PAD_0	PIN_FUNCTION_C
#define	PA01_USE_SERCOM1_PAD_1	PIN_FUNCTION_C
#define	PB08_USE_SERCOM4_PAD_0	PIN_FUNCTION_C
#define	PB09_USE_SERCOM4_PAD_1	PIN_FUNCTION_C
#define	PA04_USE_SERCOM0_PAD_0	PIN_FUNCTION_C
#define	PA05_USE_SERCOM0_PAD_1	PIN_FUNCTION_C
#define	PA06_USE_SERCOM0_PAD_2	PIN_FUNCTION_C
#define	PA07_USE_SERCOM0_PAD_3	PIN_FUNCTION_C
#define	PA08_USE_SERCOM0_PAD_0	PIN_FUNCTION_C
#define	PA09_USE_SERCOM0_PAD_1	PIN_FUNCTION_C
#define	PA10_USE_SERCOM0_PAD_2	PIN_FUNCTION_C
#define	PA11_USE_SERCOM0_PAD_3	PIN_FUNCTION_C
#define	PB10_USE_SERCOM4_PAD_2	PIN_FUNCTION_C
#define	PB11_USE_SERCOM4_PAD_3	PIN_FUNCTION_C
#define	PA12_USE_SERCOM2_PAD_0	PIN_FUNCTION_C
#define	PA13_USE_SERCOM2_PAD_1	PIN_FUNCTION_C
#define	PA14_USE_SERCOM2_PAD_2	PIN_FUNCTION_C
#define	PA15_USE_SERCOM2_PAD_3	PIN_FUNCTION_C
#define	PA16_USE_SERCOM1_PAD_0	PIN_FUNCTION_C
#define	PA17_USE_SERCOM1_PAD_1	PIN_FUNCTION_C
#define	PA18_USE_SERCOM1_PAD_2	PIN_FUNCTION_C
#define	PA19_USE_SERCOM1_PAD_3	PIN_FUNCTION_C
#define	PA20_USE_SERCOM5_PAD_2	PIN_FUNCTION_C
#define	PA21_USE_SERCOM5_PAD_3	PIN_FUNCTION_C
#define	PA22_USE_SERCOM3_PAD_0	PIN_FUNCTION_C
#define	PA23_USE_SERCOM3_PAD_1	PIN_FUNCTION_C
#define	PA24_USE_SERCOM3_PAD_2	PIN_FUNCTION_C
#define	PA25_USE_SERCOM3_PAD_3	PIN_FUNCTION_C
#define	PB22_USE_SERCOM5_PAD_2	PIN_FUNCTION_C
#define	PB23_USE_SERCOM5_PAD_3	PIN_FUNCTION_C
#define	PA30_USE_SERCOM1_PAD_2	PIN_FUNCTION_C
#define	PA31_USE_SERCOM1_PAD_3	PIN_FUNCTION_C
#define	PB02_USE_SERCOM5_PAD_0	PIN_FUNCTION_C
#define	PB03_USE_SERCOM5_PAD_1	PIN_FUNCTION_C
#define	PB12_USE_SERCOM4_PAD_0	PIN_FUNCTION_C
#define	PB13_USE_SERCOM4_PAD_1	PIN_FUNCTION_C
#define	PB14_USE_SERCOM4_PAD_2	PIN_FUNCTION_C
#define	PB15_USE_SERCOM4_PAD_3	PIN_FUNCTION_C
#define	PB16_USE_SERCOM5_PAD_0	PIN_FUNCTION_C
#define	PB17_USE_SERCOM5_PAD_1	PIN_FUNCTION_C
#define	PB30_USE_SERCOM5_PAD_0	PIN_FUNCTION_C
#define	PB31_USE_SERCOM5_PAD_1	PIN_FUNCTION_C
#define	PB00_USE_SERCOM5_PAD_2	PIN_FUNCTION_C
#define	PB01_USE_SERCOM5_PAD_3	PIN_FUNCTION_C




#define	PA08_USE_SERCOM2_PAD_0	PIN_FUNCTION_D
#define	PA09_USE_SERCOM2_PAD_1	PIN_FUNCTION_D
#define	PA10_USE_SERCOM2_PAD_2	PIN_FUNCTION_D
#define	PA11_USE_SERCOM2_PAD_3	PIN_FUNCTION_D
#define	PB10_USE_TC5_WO_0		PIN_FUNCTION_D
#define	PB11_USE_TC5_WO_1		PIN_FUNCTION_D
#define	PA12_USE_SERCOM4_PAD_0	PIN_FUNCTION_D
#define	PA13_USE_SERCOM4_PAD_1	PIN_FUNCTION_D
#define	PA14_USE_SERCOM4_PAD_2	PIN_FUNCTION_D
#define	PA15_USE_SERCOM4_PAD_3	PIN_FUNCTION_D
#define	PA16_USE_SERCOM3_PAD_0	PIN_FUNCTION_D
#define	PA17_USE_SERCOM3_PAD_1	PIN_FUNCTION_D
#define	PA18_USE_SERCOM3_PAD_2	PIN_FUNCTION_D
#define	PA19_USE_SERCOM3_PAD_3	PIN_FUNCTION_D
#define	PA20_USE_SERCOM3_PAD_2	PIN_FUNCTION_D
#define	PA21_USE_SERCOM3_PAD_3	PIN_FUNCTION_D
#define	PA22_USE_SERCOM5_PAD_0	PIN_FUNCTION_D
#define	PA23_USE_SERCOM5_PAD_1	PIN_FUNCTION_D
#define	PA24_USE_SERCOM5_PAD_2	PIN_FUNCTION_D
#define	PA25_USE_SERCOM5_PAD_3	PIN_FUNCTION_D


#define	PA00_USE_TCC2_WO_0	PIN_FUNCTION_E
#define	PA01_USE_TCC2_WO_1	PIN_FUNCTION_E
#define	PB08_USE_TC4_WO_0	PIN_FUNCTION_E
#define	PB09_USE_TC4_WO_1	PIN_FUNCTION_E
#define	PA04_USE_TCC0_WO_0	PIN_FUNCTION_E
#define	PA05_USE_TCC0_WO_1	PIN_FUNCTION_E
#define	PA06_USE_TCC1_WO_0	PIN_FUNCTION_E
#define	PA07_USE_TCC1_WO_1	PIN_FUNCTION_E
#define	PA08_USE_TCC0_WO_0	PIN_FUNCTION_E
#define	PA09_USE_TCC0_WO_1	PIN_FUNCTION_E
#define	PA10_USE_TCC1_WO_0	PIN_FUNCTION_E
#define	PA11_USE_TCC1_WO_1	PIN_FUNCTION_E
#define	PB10_USE_TCC0_WO_4	PIN_FUNCTION_E
#define	PB11_USE_TCC0_WO_5	PIN_FUNCTION_E
#define	PA12_USE_TCC2_WO_0	PIN_FUNCTION_E
#define	PA13_USE_TCC2_WO_1	PIN_FUNCTION_E
#define	PA14_USE_TC3_WO_0	PIN_FUNCTION_E
#define	PA15_USE_TC3_WO_1	PIN_FUNCTION_E
#define	PA16_USE_TCC2_WO_0	PIN_FUNCTION_E
#define	PA17_USE_TCC2_WO_1	PIN_FUNCTION_E
#define	PA18_USE_TC3_WO_0	PIN_FUNCTION_E
#define	PA19_USE_TC3_WO_1	PIN_FUNCTION_E
#define	PA20_USE_TC7_WO_0	PIN_FUNCTION_E
#define	PA21_USE_TC7_WO_1	PIN_FUNCTION_E
#define	PA22_USE_TC4_WO_0	PIN_FUNCTION_E
#define	PA23_USE_TC4_WO_1	PIN_FUNCTION_E
#define	PA24_USE_TC5_WO_0	PIN_FUNCTION_E
#define	PA25_USE_TC5_WO_1	PIN_FUNCTION_E
#define	PB22_USE_TC7_WO_0	PIN_FUNCTION_E
#define	PB23_USE_TC7_WO_1	PIN_FUNCTION_E
#define	PA30_USE_TCC1_WO_0	PIN_FUNCTION_E
#define	PA31_USE_TCC1_WO_1	PIN_FUNCTION_E
#define	PB02_USE_TC6_WO_0	PIN_FUNCTION_E
#define	PB03_USE_TC6_WO_1	PIN_FUNCTION_E
#define	PB12_USE_TC4_WO_0	PIN_FUNCTION_E
#define	PB13_USE_TC4_WO_1	PIN_FUNCTION_E
#define	PB14_USE_TC5_WO_0	PIN_FUNCTION_E
#define	PB15_USE_TC5_WO_1	PIN_FUNCTION_E
#define	PB16_USE_TC6_WO_0	PIN_FUNCTION_E
#define	PB17_USE_TC6_WO_1	PIN_FUNCTION_E
#define	PB30_USE_TCC0_WO_0	PIN_FUNCTION_E
#define	PB31_USE_TCC0_WO_1	PIN_FUNCTION_E
#define	PB00_USE_TC7_WO_0	PIN_FUNCTION_E
#define	PB01_USE_TC7_WO_1	PIN_FUNCTION_E



#define	PA08_USE_TCC1_WO_2	PIN_FUNCTION_F
#define	PA09_USE_TCC1_WO_3	PIN_FUNCTION_F
#define	PA10_USE_TCC0_WO_2	PIN_FUNCTION_F
#define	PA11_USE_TCC0_WO_3	PIN_FUNCTION_F
#define	PB10_USE_I2S_MCK_1	PIN_FUNCTION_F
#define	PB11_USE_I2S_SCK_1	PIN_FUNCTION_F
#define	PA12_USE_TCC0_WO_6	PIN_FUNCTION_F
#define	PA13_USE_TCC0_WO_7	PIN_FUNCTION_F
#define	PA14_USE_TCC0_WO_4	PIN_FUNCTION_F
#define	PA15_USE_TCC0_WO_5	PIN_FUNCTION_F
#define	PA16_USE_TCC0_WO_6	PIN_FUNCTION_F
#define	PA17_USE_TCC0_WO_7	PIN_FUNCTION_F
#define	PA18_USE_TCC0_WO_2	PIN_FUNCTION_F
#define	PA19_USE_TCC0_WO_3	PIN_FUNCTION_F
#define	PA20_USE_TCC0_WO_6	PIN_FUNCTION_F
#define	PA21_USE_TCC0_WO_7	PIN_FUNCTION_F
#define	PA22_USE_TCC0_WO_4	PIN_FUNCTION_F
#define	PA23_USE_TCC0_WO_5	PIN_FUNCTION_F
#define	PA24_USE_TCC1_WO_2	PIN_FUNCTION_F
#define	PA25_USE_TCC1_WO_3	PIN_FUNCTION_F
#define	PB22_USE_GCLK_IO_0	PIN_FUNCTION_F
#define	PB23_USE_GCLK_IO_1	PIN_FUNCTION_F
#define	PB12_USE_TCC0_WO_6	PIN_FUNCTION_F
#define	PB13_USE_TCC0_WO_7	PIN_FUNCTION_F
#define	PB14_USE_GCLK_IO_0	PIN_FUNCTION_F
#define	PB15_USE_GCLK_IO_1	PIN_FUNCTION_F
#define	PB16_USE_TCC0_WO_4	PIN_FUNCTION_F
#define	PB17_USE_TCC0_WO_5	PIN_FUNCTION_F
#define	PB30_USE_TCC1_WO_2	PIN_FUNCTION_F
#define	PB31_USE_TCC1_WO_3	PIN_FUNCTION_F



#define	PA07_USE_I2S_SD_0	PIN_FUNCTION_G
#define	PA08_USE_I2S_SD_1	PIN_FUNCTION_G
#define	PA09_USE_I2S_MCK_0	PIN_FUNCTION_G
#define	PA10_USE_I2S_SCK_0	PIN_FUNCTION_G
#define	PA11_USE_I2S_FS_0	PIN_FUNCTION_G
#define	PA19_USE_I2S_SD_0	PIN_FUNCTION_G
#define	PA20_USE_I2S_SCK_0	PIN_FUNCTION_G
#define	PA21_USE_I2S_FS_0	PIN_FUNCTION_G
#define	PA23_USE_USB_SOF_1kHz	PIN_FUNCTION_G
#define	PA24_USE_USB_DM		PIN_FUNCTION_G
#define	PA25_USE_USB_DP		PIN_FUNCTION_G
#define	PA30_USE_SWCLK		PIN_FUNCTION_G
#define	PA31_USE_SWDIO		PIN_FUNCTION_G
#define	PB12_USE_I2S_FS_1	PIN_FUNCTION_G
#define	PB13_USE_GCLK_IO_7	PIN_FUNCTION_G
#define	PB16_USE_I2S_SD_1	PIN_FUNCTION_G
#define	PB17_USE_I2S_MCK_0	PIN_FUNCTION_G
#define	PA10_USE_GCLK_IO_4	PIN_FUNCTION_H
#define	PA11_USE_GCLK_IO_5	PIN_FUNCTION_H
#define	PB10_USE_GCLK_IO_4	PIN_FUNCTION_H
#define	PB11_USE_GCLK_IO_5	PIN_FUNCTION_H
#define	PA12_USE_AC_CMP_0	PIN_FUNCTION_H
#define	PA13_USE_AC_CMP_1	PIN_FUNCTION_H
#define	PA14_USE_GCLK_IO_0	PIN_FUNCTION_H
#define	PA15_USE_GCLK_IO_1	PIN_FUNCTION_H
#define	PA16_USE_GCLK_IO_2	PIN_FUNCTION_H
#define	PA17_USE_GCLK_IO_3	PIN_FUNCTION_H
#define	PA18_USE_AC_CMP_0	PIN_FUNCTION_H
#define	PA19_USE_AC_CMP_1	PIN_FUNCTION_H
#define	PA20_USE_GCLK_IO_4	PIN_FUNCTION_H
#define	PA21_USE_GCLK_IO_5	PIN_FUNCTION_H
#define	PA22_USE_GCLK_IO_6	PIN_FUNCTION_H
#define	PA23_USE_GCLK_IO_7	PIN_FUNCTION_H
#define	PA30_USE_GCLK_IO_0	PIN_FUNCTION_H
#define	PB12_USE_GCLK_IO_6	PIN_FUNCTION_H
#define	PB16_USE_GCLK_IO_2	PIN_FUNCTION_H
#define	PB17_USE_GCLK_IO_3	PIN_FUNCTION_H





#define	GPIO_ENDMARK	GPIO_END

#define	GPIO_PA00	(PORTA_GROUP|GPIO_00)
#define	GPIO_PA01	(PORTA_GROUP|GPIO_01)
#define	GPIO_PA02	(PORTA_GROUP|GPIO_02)
#define	GPIO_PA03	(PORTA_GROUP|GPIO_03)
#define	GPIO_PA04	(PORTA_GROUP|GPIO_04)
#define	GPIO_PA05	(PORTA_GROUP|GPIO_05)
#define	GPIO_PA06	(PORTA_GROUP|GPIO_06)
#define	GPIO_PA07	(PORTA_GROUP|GPIO_07)
#define	GPIO_PA08	(PORTA_GROUP|GPIO_08)
#define	GPIO_PA09	(PORTA_GROUP|GPIO_09)
#define	GPIO_PA10	(PORTA_GROUP|GPIO_10)
#define	GPIO_PA11	(PORTA_GROUP|GPIO_11)
#define	GPIO_PA12	(PORTA_GROUP|GPIO_12)
#define	GPIO_PA13	(PORTA_GROUP|GPIO_13)
#define	GPIO_PA14	(PORTA_GROUP|GPIO_14)
#define	GPIO_PA15	(PORTA_GROUP|GPIO_15)
#define	GPIO_PA16	(PORTA_GROUP|GPIO_16)
#define	GPIO_PA17	(PORTA_GROUP|GPIO_17)
#define	GPIO_PA18	(PORTA_GROUP|GPIO_18)
#define	GPIO_PA19	(PORTA_GROUP|GPIO_19)
#define	GPIO_PA20	(PORTA_GROUP|GPIO_20)
#define	GPIO_PA21	(PORTA_GROUP|GPIO_21)
#define	GPIO_PA22	(PORTA_GROUP|GPIO_22)
#define	GPIO_PA23	(PORTA_GROUP|GPIO_23)
#define	GPIO_PA24	(PORTA_GROUP|GPIO_24)
#define	GPIO_PA25	(PORTA_GROUP|GPIO_25)
#define	GPIO_PA26	PORTA_IGNORE
#define	GPIO_PA27	(PORTA_GROUP|GPIO_27)
#define	GPIO_PA28	(PORTA_GROUP|GPIO_28)
#define	GPIO_PA29	PORTA_IGNORE
#define	GPIO_PA30	(PORTA_GROUP|GPIO_30)
#define	GPIO_PA31	(PORTA_GROUP|GPIO_31)
		
		
#define	GPIO_PB00	(PORTB_GROUP|GPIO_00)
#define	GPIO_PB01	(PORTB_GROUP|GPIO_01)
#define	GPIO_PB02	(PORTB_GROUP|GPIO_02)
#define	GPIO_PB03	(PORTB_GROUP|GPIO_03)
#define	GPIO_PB04	(PORTB_GROUP|GPIO_04)
#define	GPIO_PB05	(PORTB_GROUP|GPIO_05)
#define	GPIO_PB06	(PORTB_GROUP|GPIO_06)
#define	GPIO_PB07	(PORTB_GROUP|GPIO_07)
#define	GPIO_PB08	(PORTB_GROUP|GPIO_08)
#define	GPIO_PB09	(PORTB_GROUP|GPIO_09)
#define	GPIO_PB10	(PORTB_GROUP|GPIO_10)
#define	GPIO_PB11	(PORTB_GROUP|GPIO_11)
#define	GPIO_PB12	(PORTB_GROUP|GPIO_12)
#define	GPIO_PB13	(PORTB_GROUP|GPIO_13)
#define	GPIO_PB14	(PORTB_GROUP|GPIO_14)
#define	GPIO_PB15	(PORTB_GROUP|GPIO_15)
#define	GPIO_PB16	(PORTB_GROUP|GPIO_16)
#define	GPIO_PB17	(PORTB_GROUP|GPIO_17)
#define	GPIO_PB18	PORTA_IGNORE
#define	GPIO_PB19	PORTA_IGNORE
#define	GPIO_PB20	PORTA_IGNORE
#define	GPIO_PB21	PORTA_IGNORE
#define	GPIO_PB22	(PORTB_GROUP|GPIO_22)
#define	GPIO_PB23	(PORTB_GROUP|GPIO_23)
#define	GPIO_PB24	PORTA_IGNORE
#define	GPIO_PB25	PORTA_IGNORE
#define	GPIO_PB26	PORTA_IGNORE
#define	GPIO_PB27	PORTA_IGNORE
#define	GPIO_PB28	PORTA_IGNORE
#define	GPIO_PB29	PORTA_IGNORE
#define	GPIO_PB30	(PORTB_GROUP|GPIO_30)
#define	GPIO_PB31	(PORTB_GROUP|GPIO_31)






#endif

